name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Build and Push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: "."
        file: "Dockerfile"
        push: true
        tags: michaelilyin/orchestrator:latest
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build
    steps:
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ${{ secrets.DOCKER_SSH_HOST }}
        remote_docker_port: ${{ secrets.DOCKER_SSH_PORT }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        pull_images_first: true
